export type Business = {
  id: string;
  owner_id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  color_primary: string | null;
  color_secondary: string | null;
  typography: string | null;
  theme: string | null;
  layout_style: string | null;
  description: string | null;
  about_title: string | null;
  about_description: string | null;
  cover_image: string | null;
  banner_image: string | null;
  slogan?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  address?: string | null;
  schedule?: string | null;
  language?: string | null;
  currency?: string | null;
  plan?: string | null;
  email?: string | null;
  // Design properties
  background_color?: string | null;
  surface_color?: string | null;
  text_color?: string | null;
  accent_color?: string | null;
  font_weight?: string | null;
  category_alignment?: string | null;
  product_alignment?: string | null;
  price_alignment?: string | null;
  title_alignment?: string | null;
  card_style?: string | null;
  border_radius?: number | null;
  shadow?: string | null;
  spacing?: string | null;
  separator_style?: string | null;
  image_style?: string | null;
  button_style?: string | null;
  header_style?: string | null;
  visual_density?: string | null;
  vintage_color?: string | null;
  vintage_color_mode?: string | null;
  promo_active?: boolean;
  promo_title?: string | null;
  promo_description?: string | null;
  promo_image?: string | null;
  created_at: string;
  trial_enabled?: boolean;
};

export type Category = {
  id: string;
  business_id: string;
  name: string;
  item_order: number | null;
  is_visible: boolean | null;
  icon: string | null;
  created_at: string;
  product_count?: number;
};

export type Product = {
  id: string;
  business_id: string;
  category_id: string | null;
  name: string;
  description: string | null;
  price: number;
  image_url: string | null;
  is_available: boolean | null;
  is_featured: boolean | null;
  item_order: number | null;
  created_at: string;
  category?: Category;
};

export type Review = {
  id: string;
  business_id: string;
  first_name: string;
  last_name: string;
  comment: string;
  rating: number;
  created_at: string;
};
